/**
 * Central icon set. One import site → consistent stroke + tree-shaken bundle.
 * No emojis anywhere in the app: every glyph is a crisp lucide SVG.
 */
export {
  LayoutDashboard as IconDashboard,
  Megaphone as IconCampaign,
  PlusCircle as IconPlusCircle,
  Plus as IconPlus,
  Inbox as IconInbox,
  Send as IconSend,
  Search as IconSearch,
  MessageCircle as IconMessage,
  MessagesSquare as IconMessages,
  Bell as IconBell,
  Star as IconStar,
  Building2 as IconCompany,
  User as IconUser,
  Users as IconUsers,
  Settings as IconSettings,
  LogOut as IconLogout,
  Flag as IconFlag,
  Check as IconCheck,
  CheckCheck as IconCheckCheck,
  X as IconX,
  Pencil as IconEdit,
  Trash2 as IconTrash,
  Eye as IconEye,
  Pause as IconPause,
  Play as IconPlay,
  ArrowRight as IconArrowRight,
  ArrowLeft as IconArrowLeft,
  ChevronRight as IconChevronRight,
  ChevronDown as IconChevronDown,
  Bookmark as IconBookmark,
  SlidersHorizontal as IconFilter,
  BadgeCheck as IconVerified,
  MapPin as IconPin,
  Calendar as IconCalendar,
  ExternalLink as IconExternal,
  Upload as IconUpload,
  Image as IconImage,
  FileText as IconFile,
  Video as IconVideo,
  Menu as IconMenu,
  Sparkles as IconSparkles,
  Handshake as IconHandshake,
  ShieldCheck as IconShield,
  TrendingUp as IconTrending,
  Zap as IconZap,
  Rocket as IconRocket,
  Clock as IconClock,
  Loader2 as IconSpinner,
  Instagram as IconInstagram,
  Youtube as IconYoutube,
  Facebook as IconFacebook,
  Twitter as IconTwitter,
  Linkedin as IconLinkedin,
  Music2 as IconTiktok,
  Mail as IconMail,
  Phone as IconPhone,
  Globe as IconGlobe,
  Briefcase as IconBriefcase,
  Heart as IconHeart,
  Trophy as IconTrophy,
  Inbox as IconApplications,
  Pin as IconPin2,
  Archive as IconArchive,
  ArchiveRestore as IconUnarchive,
  BellOff as IconBellOff,
  Ban as IconBan,
  EyeOff as IconEyeOff,
  Timer as IconTimer,
  LifeBuoy as IconSupport,
  HelpCircle as IconHelp,
  Ticket as IconTicket,
  Tag as IconTag,
  Medal as IconMedal,
  Award as IconAward,
  History as IconHistory,
  Paperclip as IconAttach,
  MoreVertical as IconMore,
  AlertTriangle as IconWarning,
  UserX as IconUserX,
  Link2 as IconLink,
  Network as IconNetwork,
  Sliders as IconSliders,
  CreditCard as IconCard,
  Crown as IconCrown,
} from 'lucide-react';

import {
  Instagram,
  Youtube,
  Facebook,
  Twitter,
  Linkedin,
  Music2,
  Globe,
} from 'lucide-react';

export const PLATFORM_ICON = {
  instagram: Instagram,
  youtube: Youtube,
  facebook: Facebook,
  twitter: Twitter,
  linkedin: Linkedin,
  tiktok: Music2,
  default: Globe,
};
